<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(OsuPlayerLibraryTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\dependencies\NAudio.SDL3\src\NAudio.SDL3\NAudio.SDL3.csproj" />
    <ProjectReference Include="..\OsuPlayer.Core\OsuPlayer.Core.csproj" />
    <ProjectReference Include="..\OsuPlayer.Shared\OsuPlayer.Shared.csproj" />
    <ProjectReference Include="..\..\..\dependencies\KeyASIO.Net\src\Core\KeyAsio.Core.Audio\KeyAsio.Core.Audio.csproj" />
    <ProjectReference Include="..\..\..\dependencies\KeyASIO.Net\src\Core\KeyAsio.Core.OsuAudio\KeyAsio.Core.OsuAudio.csproj" />
    <ProjectReference Include="..\..\..\dependencies\ManagedSoundTouch\ManagedSoundTouch\ManagedSoundTouch.csproj" />
    <ProjectReference Include="..\..\..\dependencies\BemaniUtils.Net\IIDXAudioGenerator\IIDXAudioGenerator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="default\**\*.wav" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Coosu.Beatmap" Version="$(CoosuBeatmapVersion)" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="NLog" Version="6.1.3" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.InteropServices.GuidAttribute">
      <_Parameter1>3cd240f8-da65-44f0-ab58-d78f58109786</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
