<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(OsuPlayerWindowsTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OsuPlayer.Shared\OsuPlayer.Shared.csproj" />
    <ProjectReference Include="..\OsuPlayer.Core\OsuPlayer.Core.csproj" />
    <ProjectReference Include="..\OsuPlayer.Media.Audio\OsuPlayer.Media.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Coosu.Beatmap" Version="$(CoosuBeatmapVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.1" />
  </ItemGroup>

</Project>
