<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(OsuPlayerLibraryTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.InteropServices.GuidAttribute">
      <_Parameter1>c842fab3-ec80-4e95-b402-bf0572f1806d</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
