// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Milky.OsuPlayer.Data;

#nullable disable

namespace Milky.OsuPlayer.Data.Migrations
{
    [DbContext(typeof(OsuPlayerDbContext))]
    [Migration("20260528054433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.Beatmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT")
                        .HasColumnName("artist");

                    b.Property<string>("ArtistUnicode")
                        .HasColumnType("TEXT")
                        .HasColumnName("artistU");

                    b.Property<string>("AudioFileName")
                        .HasColumnType("TEXT")
                        .HasColumnName("audioName");

                    b.Property<int>("AudioPreviewTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("audioPreview");

                    b.Property<string>("BeatmapFileName")
                        .HasColumnType("TEXT")
                        .HasColumnName("fileName");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beatmapId");

                    b.Property<int>("BeatmapSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beatmapSetId");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT")
                        .HasColumnName("creator");

                    b.Property<double>("DiffSrNoneCtB")
                        .HasColumnType("REAL")
                        .HasColumnName("diffSrCtb");

                    b.Property<double>("DiffSrNoneMania")
                        .HasColumnType("REAL")
                        .HasColumnName("diffSrMania");

                    b.Property<double>("DiffSrNoneStandard")
                        .HasColumnType("REAL")
                        .HasColumnName("diffSrStd");

                    b.Property<double>("DiffSrNoneTaiko")
                        .HasColumnType("REAL")
                        .HasColumnName("diffSrTaiko");

                    b.Property<int>("DrainTimeSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drainTime");

                    b.Property<string>("FolderName")
                        .HasColumnType("TEXT")
                        .HasColumnName("folderName");

                    b.Property<byte>("GameMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gameMode");

                    b.Property<bool>("InOwnDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("own");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastModified");

                    b.Property<string>("SongSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SongTags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TitleUnicode")
                        .HasColumnType("TEXT")
                        .HasColumnName("titleU");

                    b.Property<int>("TotalTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("totalTime");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FolderName", "Version", "InOwnDb")
                        .HasDatabaseName("IX_beatmap_identity");

                    b.ToTable("beatmap", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.BeatmapSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ExportFile")
                        .HasColumnType("TEXT")
                        .HasColumnName("exportFile");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<bool>("InOwnDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ownDb");

                    b.Property<DateTime?>("LastPlayTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastPlayTime");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("offset");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("map_info", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.Collection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("createTime");

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(700)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagePath");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("index");

                    b.Property<int>("Locked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("collection", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.CollectionRelation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AddTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("addTime");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("collectionId");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mapId");

                    b.HasKey("Id");

                    b.ToTable("collection_relation", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.MapThumb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mapId");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbPath");

                    b.HasKey("Id");

                    b.ToTable("map_thumb", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.StoryboardInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<bool>("InOwnDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("own");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mapId");

                    b.Property<string>("SbThumbPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbPath");

                    b.Property<string>("SbThumbVideoPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbVideoPath");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("sb_info", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
