// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Milky.OsuPlayer.Data;

#nullable disable

namespace Milky.OsuPlayer.Data.Migrations
{
    [DbContext(typeof(OsuPlayerDbContext))]
    partial class OsuPlayerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.Beatmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT")
                        .HasColumnName("artist");

                    b.Property<string>("ArtistUnicode")
                        .HasColumnType("TEXT")
                        .HasColumnName("artist_unicode");

                    b.Property<string>("AudioFileName")
                        .HasColumnType("TEXT")
                        .HasColumnName("audio_file_name");

                    b.Property<int>("AudioPreviewTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preview_time_ms");

                    b.Property<string>("BeatmapFileName")
                        .HasColumnType("TEXT")
                        .HasColumnName("beatmap_file_name");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("osu_beatmap_id");

                    b.Property<int>("BeatmapSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("osu_beatmapset_id");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT")
                        .HasColumnName("creator");

                    b.Property<double>("DiffSrNoneCtB")
                        .HasColumnType("REAL")
                        .HasColumnName("star_rating_catch");

                    b.Property<double>("DiffSrNoneMania")
                        .HasColumnType("REAL")
                        .HasColumnName("star_rating_mania");

                    b.Property<double>("DiffSrNoneStandard")
                        .HasColumnType("REAL")
                        .HasColumnName("star_rating_standard");

                    b.Property<double>("DiffSrNoneTaiko")
                        .HasColumnType("REAL")
                        .HasColumnName("star_rating_taiko");

                    b.Property<int>("DrainTimeSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drain_time_seconds");

                    b.Property<string>("FolderName")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_name");

                    b.Property<byte>("GameMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_mode");

                    b.Property<bool>("InOwnDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_local");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("SongSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SongTags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TitleUnicode")
                        .HasColumnType("TEXT")
                        .HasColumnName("title_unicode");

                    b.Property<int>("TotalTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_time_ms");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT")
                        .HasColumnName("difficulty_name");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapSetId")
                        .HasDatabaseName("ix_beatmaps_osu_beatmapset_id");

                    b.HasIndex("FolderName")
                        .HasDatabaseName("ix_beatmaps_folder_name");

                    b.HasIndex("FolderName", "Version", "InOwnDb")
                        .IsUnique()
                        .HasDatabaseName("ux_beatmaps_identity");

                    b.ToTable("beatmaps", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.BeatmapSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ExportFile")
                        .HasColumnType("TEXT")
                        .HasColumnName("exported_file_path");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_name");

                    b.Property<bool>("InOwnDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_local");

                    b.Property<DateTime?>("LastPlayTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_played_at");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("audio_offset_ms");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("difficulty_name");

                    b.HasKey("Id");

                    b.HasIndex("ExportFile")
                        .HasDatabaseName("ix_beatmap_play_settings_exported_file_path");

                    b.HasIndex("LastPlayTime")
                        .HasDatabaseName("ix_beatmap_play_settings_last_played_at");

                    b.HasIndex("FolderName", "Version", "InOwnDb")
                        .IsUnique()
                        .HasDatabaseName("ux_beatmap_play_settings_identity");

                    b.ToTable("beatmap_play_settings", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.Collection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(700)
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_image_path");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<int>("Locked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Index")
                        .HasDatabaseName("ix_collections_sort_order");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_collections_name");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.CollectionRelation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AddTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("collection_id");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("beatmap_settings_id");

                    b.HasKey("Id");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_collection_beatmaps_beatmap_settings_id");

                    b.HasIndex("CollectionId", "MapId")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_beatmaps_collection_map");

                    b.ToTable("collection_beatmaps", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.MapThumb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("MapId")
                        .HasColumnType("TEXT")
                        .HasColumnName("beatmap_id");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_path");

                    b.HasKey("Id");

                    b.HasIndex("MapId")
                        .IsUnique()
                        .HasDatabaseName("ux_beatmap_thumbnails_beatmap_id");

                    b.ToTable("beatmap_thumbnails", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.StoryboardInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_name");

                    b.Property<bool>("InOwnDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_local");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("beatmap_id");

                    b.Property<string>("SbThumbPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_path");

                    b.Property<string>("SbThumbVideoPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_video_path");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("difficulty_name");

                    b.HasKey("Id");

                    b.HasIndex("MapId")
                        .IsUnique()
                        .HasDatabaseName("ux_storyboard_assets_beatmap_id");

                    b.ToTable("storyboard_assets", (string)null);
                });

            modelBuilder.Entity("Milky.OsuPlayer.Data.Models.CollectionRelation", b =>
                {
                    b.HasOne("Milky.OsuPlayer.Data.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Milky.OsuPlayer.Data.Models.BeatmapSettings", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
