GeneralSection:
  RunOnStartup: false
  DbPath: 
  CustomSongDir: D:\GitHub\Osu-Player\src\Songs
  ExitWhenClosed: 
  Locale: 
  OsuSongDir: D:\GitHub\Osu-Player\src\Songs
  LastMigrateVersion: 
VolumeSection:
  MainVolume: 1
  MusicVolume: 0.5
  HitsoundVolume: 0.5
  SampleVolume: 0.5
  BalanceFactor: 1
PlaySection:
  GeneralOffset: 0
  ReplacePlayList: true
  PlaybackRate: 1
  PlayUseTempo: false
  AutoPlay: false
  DeviceInfo: 
  DesiredLatency: 5
  IsExclusive: false
  PlayListMode: Normal
LyricSection:
  IsDesktopLyricEnabled: true
  IsDesktopLyricLocked: true
  LyricSource: Auto
  ProvideType: Original
  StrictMode: true
  EnableCache: true
  FontFamily: 
  Hue: 0
  Saturation: 0
  Lightness: 0
ExportSection:
  MusicDir: D:\GitHub\Osu-Player\src\exports\music
  BackgroundDir: D:\GitHub\Osu-Player\src\exports\background
  ExportNamingStyle: ArtistTitle
  ExportGroupStyle: Artist
HotKeys:
  TogglePlay: ''
  PrevSong: ''
  NextSong: ''
  VolumeUp: ''
  VolumeDown: ''
  SwitchFullMiniMode: ''
  AddCurrentToFav: ''
  SwitchLyricWindow: ''
