//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsuPlayer.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsuPlayer.Lang.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error while loading beatmap 的本地化字符串。
        /// </summary>
        internal static string Err_Beatmap_Load {
            get {
                return ResourceManager.GetString("Err_Beatmap_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection is not in database 的本地化字符串。
        /// </summary>
        internal static string Err_CollectionNotInDb {
            get {
                return ResourceManager.GetString("Err_CollectionNotInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while scanning custom folder 的本地化字符串。
        /// </summary>
        internal static string Err_Custom_Scan {
            get {
                return ResourceManager.GetString("Err_Custom_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录不存在 的本地化字符串。
        /// </summary>
        internal static string Err_DirNotFound {
            get {
                return ResourceManager.GetString("Err_DirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while syncing IIDX music_data.bin 的本地化字符串。
        /// </summary>
        internal static string Err_IidxMusicData_Sync {
            get {
                return ResourceManager.GetString("Err_IidxMusicData_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The beatmap is not in database 的本地化字符串。
        /// </summary>
        internal static string Err_MapNotInDb {
            get {
                return ResourceManager.GetString("Err_MapNotInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while syncing osu!db 的本地化字符串。
        /// </summary>
        internal static string Err_Osudb_Sync {
            get {
                return ResourceManager.GetString("Err_Osudb_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while checking for update 的本地化字符串。
        /// </summary>
        internal static string Err_Update_Check {
            get {
                return ResourceManager.GetString("Err_Update_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        internal static string ExcWin_Btn_Continue {
            get {
                return ResourceManager.GetString("ExcWin_Btn_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string ExcWin_Btn_Exit {
            get {
                return ResourceManager.GetString("ExcWin_Btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception Information: (Will send to developer) 的本地化字符串。
        /// </summary>
        internal static string ExcWin_ExcInfoHeader {
            get {
                return ResourceManager.GetString("ExcWin_ExcInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something went wrong. 的本地化字符串。
        /// </summary>
        internal static string ExcWin_Subtitle {
            get {
                return ResourceManager.GetString("ExcWin_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 But you can still continue during this session. 的本地化字符串。
        /// </summary>
        internal static string ExcWin_Subtitle_Continuable {
            get {
                return ResourceManager.GetString("ExcWin_Subtitle_Continuable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oops! 的本地化字符串。
        /// </summary>
        internal static string ExcWin_Title {
            get {
                return ResourceManager.GetString("ExcWin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统默认 的本地化字符串。
        /// </summary>
        internal static string Language_SystemDefault {
            get {
                return ResourceManager.GetString("Language_SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误  的本地化字符串。
        /// </summary>
        internal static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string Text_Info {
            get {
                return ResourceManager.GetString("Text_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Text_Warn {
            get {
                return ResourceManager.GetString("Text_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D音效 的本地化字符串。
        /// </summary>
        internal static string Ui_3dSoundEffect {
            get {
                return ResourceManager.GetString("Ui_3dSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新的收藏夹 的本地化字符串。
        /// </summary>
        internal static string Ui_AddNewCollection {
            get {
                return ResourceManager.GetString("Ui_AddNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艺术家 的本地化字符串。
        /// </summary>
        internal static string Ui_Artist {
            get {
                return ResourceManager.GetString("Ui_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string Ui_Auto {
            get {
                return ResourceManager.GetString("Ui_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D音效方法 的本地化字符串。
        /// </summary>
        internal static string Ui_BalanceMode {
            get {
                return ResourceManager.GetString("Ui_BalanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介 的本地化字符串。
        /// </summary>
        internal static string Ui_BriefIntroduction {
            get {
                return ResourceManager.GetString("Ui_BriefIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消扫描 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_CancelScan {
            get {
                return ResourceManager.GetString("Ui_Btn_CancelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_CheckUpdate {
            get {
                return ResourceManager.GetString("Ui_Btn_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空列表 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_ClearList {
            get {
                return ResourceManager.GetString("Ui_Btn_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部删除 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_DeleteAll {
            get {
                return ResourceManager.GetString("Ui_Btn_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑封面 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_EditCover {
            get {
                return ResourceManager.GetString("Ui_Btn_EditCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部导出 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_ExportAll {
            get {
                return ResourceManager.GetString("Ui_Btn_ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开目录 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_OpenDirectory {
            get {
                return ResourceManager.GetString("Ui_Btn_OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部播放 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_PlayAll {
            get {
                return ResourceManager.GetString("Ui_Btn_PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部排队 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_QueueAll {
            get {
                return ResourceManager.GetString("Ui_Btn_QueueAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_Save {
            get {
                return ResourceManager.GetString("Ui_Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部收藏 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_SaveAll {
            get {
                return ResourceManager.GetString("Ui_Btn_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动扫描 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_ScanManually {
            get {
                return ResourceManager.GetString("Ui_Btn_ScanManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动同步 的本地化字符串。
        /// </summary>
        internal static string Ui_Btn_SyncManually {
            get {
                return ResourceManager.GetString("Ui_Btn_SyncManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Ui_Cancel {
            get {
                return ResourceManager.GetString("Ui_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Ui_Close {
            get {
                return ResourceManager.GetString("Ui_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭桌面歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_CloseDesktopLyric {
            get {
                return ResourceManager.GetString("Ui_CloseDesktopLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏夹名 的本地化字符串。
        /// </summary>
        internal static string Ui_CollectionName {
            get {
                return ResourceManager.GetString("Ui_CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string Ui_CreateTime {
            get {
                return ResourceManager.GetString("Ui_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        internal static string Ui_Creator {
            get {
                return ResourceManager.GetString("Ui_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_Export {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开成绩页 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_OpenScorePage {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_OpenScorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开所在目录 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_OpenSourceFolder {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_OpenSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从列表中移除 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_RemoveFromList {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏至 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_SaveTo {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_SaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索艺术家 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_SearchArtist {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_SearchArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索作者 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_SearchCreator {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_SearchCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索来源 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_SearchSource {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_SearchSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索标题 的本地化字符串。
        /// </summary>
        internal static string Ui_CtxMenu_SearchTitle {
            get {
                return ResourceManager.GetString("Ui_CtxMenu_SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单曲偏移 的本地化字符串。
        /// </summary>
        internal static string Ui_CurrentMapOffset {
            get {
                return ResourceManager.GetString("Ui_CurrentMapOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除导出文件 的本地化字符串。
        /// </summary>
        internal static string Ui_DeleteExported {
            get {
                return ResourceManager.GetString("Ui_DeleteExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_DesktopLyric {
            get {
                return ResourceManager.GetString("Ui_DesktopLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真的要删除全部吗？ 的本地化字符串。
        /// </summary>
        internal static string Ui_EnsureRemoveAll {
            get {
                return ResourceManager.GetString("Ui_EnsureRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除收藏夹？ 的本地化字符串。
        /// </summary>
        internal static string Ui_EnsureRemoveCollection {
            get {
                return ResourceManager.GetString("Ui_EnsureRemoveCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Ui_Exit {
            get {
                return ResourceManager.GetString("Ui_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新导出 的本地化字符串。
        /// </summary>
        internal static string Ui_ExportAgain {
            get {
                return ResourceManager.GetString("Ui_ExportAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导出 的本地化字符串。
        /// </summary>
        internal static string Ui_Exported {
            get {
                return ResourceManager.GetString("Ui_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在进行 的本地化字符串。
        /// </summary>
        internal static string Ui_Exporting {
            get {
                return ResourceManager.GetString("Ui_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出目录 的本地化字符串。
        /// </summary>
        internal static string Ui_ExportPath {
            get {
                return ResourceManager.GetString("Ui_ExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出时间 的本地化字符串。
        /// </summary>
        internal static string Ui_ExportTime {
            get {
                return ResourceManager.GetString("Ui_ExportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索收藏夹音乐... 的本地化字符串。
        /// </summary>
        internal static string Ui_Hint_SearchCollectionMusic3Dot {
            get {
                return ResourceManager.GetString("Ui_Hint_SearchCollectionMusic3Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题、艺术家、Mapper、来源、标签、收藏 的本地化字符串。
        /// </summary>
        internal static string Ui_Hint_SearchPageBox {
            get {
                return ResourceManager.GetString("Ui_Hint_SearchPageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色相 的本地化字符串。
        /// </summary>
        internal static string Ui_Hue {
            get {
                return ResourceManager.GetString("Ui_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酷狗音乐 的本地化字符串。
        /// </summary>
        internal static string Ui_KugouMusic {
            get {
                return ResourceManager.GetString("Ui_KugouMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度 的本地化字符串。
        /// </summary>
        internal static string Ui_Lightness {
            get {
                return ResourceManager.GetString("Ui_Lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限频器方法 的本地化字符串。
        /// </summary>
        internal static string Ui_LimiterType {
            get {
                return ResourceManager.GetString("Ui_LimiterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_LockLyric {
            get {
                return ResourceManager.GetString("Ui_LockLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 难度 的本地化字符串。
        /// </summary>
        internal static string Ui_MapDifficulty {
            get {
                return ResourceManager.GetString("Ui_MapDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30字符以内 的本地化字符串。
        /// </summary>
        internal static string Ui_Max30Char {
            get {
                return ResourceManager.GetString("Ui_Max30Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迷你模式 的本地化字符串。
        /// </summary>
        internal static string Ui_MiniMode {
            get {
                return ResourceManager.GetString("Ui_MiniMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌曲数 的本地化字符串。
        /// </summary>
        internal static string Ui_MusicCount {
            get {
                return ResourceManager.GetString("Ui_MusicCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏夹 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Collection {
            get {
                return ResourceManager.GetString("Ui_Nav_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探索 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Explore {
            get {
                return ResourceManager.GetString("Ui_Nav_Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出管理 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Export {
            get {
                return ResourceManager.GetString("Ui_Nav_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Library {
            get {
                return ResourceManager.GetString("Ui_Nav_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Mine {
            get {
                return ResourceManager.GetString("Ui_Nav_Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Music {
            get {
                return ResourceManager.GetString("Ui_Nav_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近播放 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Recent {
            get {
                return ResourceManager.GetString("Ui_Nav_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Search {
            get {
                return ResourceManager.GetString("Ui_Nav_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 故事版 的本地化字符串。
        /// </summary>
        internal static string Ui_Nav_Storyboard {
            get {
                return ResourceManager.GetString("Ui_Nav_Storyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网易云音乐 的本地化字符串。
        /// </summary>
        internal static string Ui_NeteaseMusic {
            get {
                return ResourceManager.GetString("Ui_NeteaseMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Song 的本地化字符串。
        /// </summary>
        internal static string Ui_Next {
            get {
                return ResourceManager.GetString("Ui_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一首 的本地化字符串。
        /// </summary>
        internal static string Ui_NextMusic {
            get {
                return ResourceManager.GetString("Ui_NextMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string Ui_No {
            get {
                return ResourceManager.GetString("Ui_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无 的本地化字符串。
        /// </summary>
        internal static string Ui_None {
            get {
                return ResourceManager.GetString("Ui_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Ui_Ok {
            get {
                return ResourceManager.GetString("Ui_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        internal static string Ui_Open {
            get {
                return ResourceManager.GetString("Ui_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开桌面歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_OpenDesktopLyric {
            get {
                return ResourceManager.GetString("Ui_OpenDesktopLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件所在目录 的本地化字符串。
        /// </summary>
        internal static string Ui_OpenFileFolder {
            get {
                return ResourceManager.GetString("Ui_OpenFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string Ui_Pause {
            get {
                return ResourceManager.GetString("Ui_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放 的本地化字符串。
        /// </summary>
        internal static string Ui_Play {
            get {
                return ResourceManager.GetString("Ui_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev Song 的本地化字符串。
        /// </summary>
        internal static string Ui_Prev {
            get {
                return ResourceManager.GetString("Ui_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一首 的本地化字符串。
        /// </summary>
        internal static string Ui_PrevMusic {
            get {
                return ResourceManager.GetString("Ui_PrevMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ音乐 的本地化字符串。
        /// </summary>
        internal static string Ui_QqMusic {
            get {
                return ResourceManager.GetString("Ui_QqMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 饱和度 的本地化字符串。
        /// </summary>
        internal static string Ui_Saturation {
            get {
                return ResourceManager.GetString("Ui_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Music... 的本地化字符串。
        /// </summary>
        internal static string Ui_SearchCollectionMusic3Dot {
            get {
                return ResourceManager.GetString("Ui_SearchCollectionMusic3Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets {
            get {
                return ResourceManager.GetString("Ui_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_About {
            get {
                return ResourceManager.GetString("Ui_Sets_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Common {
            get {
                return ResourceManager.GetString("Ui_Sets_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加到最喜爱的 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_AddToFavorite {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_AddToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已是最新版本。 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_AlreadyNewest {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_AlreadyNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序启动时自动播放 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_AutoPlayOnProgramStartup {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_AutoPlayOnProgramStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景目录 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_BgDirectory {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_BgDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_CheckUpdate {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立刻升级 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_ClickToUpdate {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_ClickToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_CurrentVersion {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按艺术家（Artist）分目录 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_DirGroupByArtist {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_DirGroupByArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按作者（Mapper）分目录 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_DirGroupByMapper {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_DirGroupByMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按来源（Source）分目录 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_DirGroupBySource {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_DirGroupBySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不分目录 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_DirNoGroup {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_DirNoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示全部歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_DisplayAllLyrics {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_DisplayAllLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用桌面歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_EnableDesktopLyric {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_EnableDesktopLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用严格匹配 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_EnableStrictMatching {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_EnableStrictMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新时出错。 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_ErrorWhileCheckingUpdate {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_ErrorWhileCheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出程序 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_ExitProgram {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_ExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意见反馈 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_Feedback {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新版本 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_HasNewVersion {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_HasNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次检查时间 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_LastCheckTime {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_LastCheckTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可信息 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_LicenseInfo {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化到系统托盘 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_MinToNotificationPanel {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_MinToNotificationPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐目录 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_MusicDirectory {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_MusicDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从未 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_Never {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新版本 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_NewVersion {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偏好源歌词（仅Netease源有效） 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_PreferOriginLyricNeteaseOnly {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_PreferOriginLyricNeteaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偏好翻译歌词（仅Netease源有效） 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_PreferTranslateLyricNeteaseOnly {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_PreferTranslateLyricNeteaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐私政策 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目地址 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_ProjectUrl {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新说明 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_ReleaseNote {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新详情页 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_ReleasePage {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_ReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后提醒我 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_RemindLater {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_RemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序启动时恢复上次播放 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_ResumePlaylistOnProgramStartup {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_ResumePlaylistOnProgramStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自动运行 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_RunOnStartup {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在扫描... 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_Scanning3Dot {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_Scanning3Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置默认选项 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_SetAsDefaultOptions {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_SetAsDefaultOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过此版本 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_SkipVersion {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_SkipVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统默认 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Content_SystemDefault {
            get {
                return ResourceManager.GetString("Ui_Sets_Content_SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Export {
            get {
                return ResourceManager.GetString("Ui_Sets_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HotKey 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_HotKey {
            get {
                return ResourceManager.GetString("Ui_Sets_HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Interface {
            get {
                return ResourceManager.GetString("Ui_Sets_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lyric 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Lyric {
            get {
                return ResourceManager.GetString("Ui_Sets_Lyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Nav_About {
            get {
                return ResourceManager.GetString("Ui_Sets_Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Nav_Common {
            get {
                return ResourceManager.GetString("Ui_Sets_Nav_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Nav_Export {
            get {
                return ResourceManager.GetString("Ui_Sets_Nav_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热键 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Nav_HotKey {
            get {
                return ResourceManager.GetString("Ui_Sets_Nav_HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Nav_Interface {
            get {
                return ResourceManager.GetString("Ui_Sets_Nav_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Nav_Lyric {
            get {
                return ResourceManager.GetString("Ui_Sets_Nav_Lyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Nav_Playing {
            get {
                return ResourceManager.GetString("Ui_Sets_Nav_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Playing {
            get {
                return ResourceManager.GetString("Ui_Sets_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音频播放设备 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_AudioPlayDevice {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_AudioPlayDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动播放 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_AutoPlay {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭窗体 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_CloseWindow {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义曲库路径 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_CustomSongPath {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_CustomSongPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_DesktopLyric {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_DesktopLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录分类 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_DirectoryGrouping {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_DirectoryGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出目录 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_ExportPath {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_ExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件命名格式 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_FileNamingFormat {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_FileNamingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局音效延迟 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_GlobalHitsoundDelay {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_GlobalHitsoundDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热键设置 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_HotKeySettings {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_HotKeySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IIDX music_data.bin 位置 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_IidxMusicDataLocation {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_IidxMusicDataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_Language {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌词源 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_LyricSource {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_LyricSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配模式 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_MatchMode {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_MatchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低配模式 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_MinimalEffectMode {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_MinimalEffectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 osu!db位置 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_OsuDbLocation {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_OsuDbLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放进度 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_PlayProgress {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_PlayProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件更新 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_SoftwareUpdate {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_Startup {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译 的本地化字符串。
        /// </summary>
        internal static string Ui_Sets_Title_Translation {
            get {
                return ResourceManager.GetString("Ui_Sets_Title_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string Ui_Size {
            get {
                return ResourceManager.GetString("Ui_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首 的本地化字符串。
        /// </summary>
        internal static string Ui_SongsClassifier {
            get {
                return ResourceManager.GetString("Ui_SongsClassifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始扫描 ! 的本地化字符串。
        /// </summary>
        internal static string Ui_StartScan {
            get {
                return ResourceManager.GetString("Ui_StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 故事板 的本地化字符串。
        /// </summary>
        internal static string Ui_Storyboard {
            get {
                return ResourceManager.GetString("Ui_Storyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        internal static string Ui_Switch {
            get {
                return ResourceManager.GetString("Ui_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        internal static string Ui_SwitchOff {
            get {
                return ResourceManager.GetString("Ui_SwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        internal static string Ui_SwitchOn {
            get {
                return ResourceManager.GetString("Ui_SwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐列表 的本地化字符串。
        /// </summary>
        internal static string Ui_Tab_MusicList {
            get {
                return ResourceManager.GetString("Ui_Tab_MusicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的收藏 的本地化字符串。
        /// </summary>
        internal static string Ui_Tab_MyCollection {
            get {
                return ResourceManager.GetString("Ui_Tab_MyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string Ui_Title {
            get {
                return ResourceManager.GetString("Ui_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 的本地化字符串。
        /// </summary>
        internal static string Ui_Total {
            get {
                return ResourceManager.GetString("Ui_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁歌词 的本地化字符串。
        /// </summary>
        internal static string Ui_UnlockLyric {
            get {
                return ResourceManager.GetString("Ui_UnlockLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量- 的本地化字符串。
        /// </summary>
        internal static string Ui_VolumeDown {
            get {
                return ResourceManager.GetString("Ui_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总体 的本地化字符串。
        /// </summary>
        internal static string Ui_VolumeMaster {
            get {
                return ResourceManager.GetString("Ui_VolumeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐 的本地化字符串。
        /// </summary>
        internal static string Ui_VolumeMusic {
            get {
                return ResourceManager.GetString("Ui_VolumeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音轨 的本地化字符串。
        /// </summary>
        internal static string Ui_VolumeSample {
            get {
                return ResourceManager.GetString("Ui_VolumeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音效 的本地化字符串。
        /// </summary>
        internal static string Ui_VolumeSound {
            get {
                return ResourceManager.GetString("Ui_VolumeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量+ 的本地化字符串。
        /// </summary>
        internal static string Ui_VolumeUp {
            get {
                return ResourceManager.GetString("Ui_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择osu!db,同步曲库 的本地化字符串。
        /// </summary>
        internal static string Ui_Welcome_SelectDb {
            get {
                return ResourceManager.GetString("Ui_Welcome_SelectDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过此步 的本地化字符串。
        /// </summary>
        internal static string Ui_Welcome_Skip {
            get {
                return ResourceManager.GetString("Ui_Welcome_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择以下项目,开启精彩音乐世界 的本地化字符串。
        /// </summary>
        internal static string Ui_Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Ui_Welcome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎 的本地化字符串。
        /// </summary>
        internal static string Ui_Welcome_Title {
            get {
                return ResourceManager.GetString("Ui_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启曲库目录监听服务,减少同步与扫描时间 的本地化字符串。
        /// </summary>
        internal static string Ui_Wenable_Watcher {
            get {
                return ResourceManager.GetString("Ui_Wenable_Watcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭确认 的本地化字符串。
        /// </summary>
        internal static string Ui_Win_Closing {
            get {
                return ResourceManager.GetString("Ui_Win_Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑收藏 的本地化字符串。
        /// </summary>
        internal static string Ui_Win_EditCollection {
            get {
                return ResourceManager.GetString("Ui_Win_EditCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建收藏 的本地化字符串。
        /// </summary>
        internal static string Ui_Win_NewCollection {
            get {
                return ResourceManager.GetString("Ui_Win_NewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择收藏 的本地化字符串。
        /// </summary>
        internal static string Ui_Win_SelectCollection {
            get {
                return ResourceManager.GetString("Ui_Win_SelectCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择难度 的本地化字符串。
        /// </summary>
        internal static string Ui_Win_SelectDifficulty {
            get {
                return ResourceManager.GetString("Ui_Win_SelectDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放器设置 的本地化字符串。
        /// </summary>
        internal static string Ui_Win_Sets {
            get {
                return ResourceManager.GetString("Ui_Win_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Ui_Yes {
            get {
                return ResourceManager.GetString("Ui_Yes", resourceCulture);
            }
        }
    }
}
