//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the OsuPlayer localization migration script.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace OsuPlayer.Lang
{
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("OsuPlayer.LocalizationMigration", "1.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class SR
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        internal SR()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                return resourceMan ??= new ResourceManager("OsuPlayer.Lang.SR", typeof(SR).Assembly);
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string Err_Beatmap_Load => ResourceManager.GetString("Err_Beatmap_Load", resourceCulture) ?? string.Empty;

        internal static string Err_CollectionNotInDb => ResourceManager.GetString("Err_CollectionNotInDb", resourceCulture) ?? string.Empty;

        internal static string Err_Custom_Scan => ResourceManager.GetString("Err_Custom_Scan", resourceCulture) ?? string.Empty;

        internal static string Err_DirNotFound => ResourceManager.GetString("Err_DirNotFound", resourceCulture) ?? string.Empty;

        internal static string Err_MapNotInDb => ResourceManager.GetString("Err_MapNotInDb", resourceCulture) ?? string.Empty;

        internal static string Err_Osudb_Sync => ResourceManager.GetString("Err_Osudb_Sync", resourceCulture) ?? string.Empty;

        internal static string Err_Update_Check => ResourceManager.GetString("Err_Update_Check", resourceCulture) ?? string.Empty;

        internal static string ExcWin_Btn_Continue => ResourceManager.GetString("ExcWin_Btn_Continue", resourceCulture) ?? string.Empty;

        internal static string ExcWin_Btn_Exit => ResourceManager.GetString("ExcWin_Btn_Exit", resourceCulture) ?? string.Empty;

        internal static string ExcWin_ExcInfoHeader => ResourceManager.GetString("ExcWin_ExcInfoHeader", resourceCulture) ?? string.Empty;

        internal static string ExcWin_Subtitle => ResourceManager.GetString("ExcWin_Subtitle", resourceCulture) ?? string.Empty;

        internal static string ExcWin_Subtitle_Continuable => ResourceManager.GetString("ExcWin_Subtitle_Continuable", resourceCulture) ?? string.Empty;

        internal static string ExcWin_Title => ResourceManager.GetString("ExcWin_Title", resourceCulture) ?? string.Empty;

        internal static string Language_SystemDefault => ResourceManager.GetString("Language_SystemDefault", resourceCulture) ?? string.Empty;

        internal static string Text_Error => ResourceManager.GetString("Text_Error", resourceCulture) ?? string.Empty;

        internal static string Text_Info => ResourceManager.GetString("Text_Info", resourceCulture) ?? string.Empty;

        internal static string Text_Warn => ResourceManager.GetString("Text_Warn", resourceCulture) ?? string.Empty;

        internal static string Ui_3dSoundEffect => ResourceManager.GetString("Ui_3dSoundEffect", resourceCulture) ?? string.Empty;

        internal static string Ui_AddNewCollection => ResourceManager.GetString("Ui_AddNewCollection", resourceCulture) ?? string.Empty;

        internal static string Ui_Artist => ResourceManager.GetString("Ui_Artist", resourceCulture) ?? string.Empty;

        internal static string Ui_Auto => ResourceManager.GetString("Ui_Auto", resourceCulture) ?? string.Empty;

        internal static string Ui_BalanceMode => ResourceManager.GetString("Ui_BalanceMode", resourceCulture) ?? string.Empty;

        internal static string Ui_BriefIntroduction => ResourceManager.GetString("Ui_BriefIntroduction", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_CancelScan => ResourceManager.GetString("Ui_Btn_CancelScan", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_CheckUpdate => ResourceManager.GetString("Ui_Btn_CheckUpdate", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_ClearList => ResourceManager.GetString("Ui_Btn_ClearList", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_DeleteAll => ResourceManager.GetString("Ui_Btn_DeleteAll", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_EditCover => ResourceManager.GetString("Ui_Btn_EditCover", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_ExportAll => ResourceManager.GetString("Ui_Btn_ExportAll", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_OpenDirectory => ResourceManager.GetString("Ui_Btn_OpenDirectory", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_PlayAll => ResourceManager.GetString("Ui_Btn_PlayAll", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_QueueAll => ResourceManager.GetString("Ui_Btn_QueueAll", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_Save => ResourceManager.GetString("Ui_Btn_Save", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_SaveAll => ResourceManager.GetString("Ui_Btn_SaveAll", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_ScanManually => ResourceManager.GetString("Ui_Btn_ScanManually", resourceCulture) ?? string.Empty;

        internal static string Ui_Btn_SyncManually => ResourceManager.GetString("Ui_Btn_SyncManually", resourceCulture) ?? string.Empty;

        internal static string Ui_Cancel => ResourceManager.GetString("Ui_Cancel", resourceCulture) ?? string.Empty;

        internal static string Ui_Close => ResourceManager.GetString("Ui_Close", resourceCulture) ?? string.Empty;

        internal static string Ui_CloseDesktopLyric => ResourceManager.GetString("Ui_CloseDesktopLyric", resourceCulture) ?? string.Empty;

        internal static string Ui_CollectionName => ResourceManager.GetString("Ui_CollectionName", resourceCulture) ?? string.Empty;

        internal static string Ui_CreateTime => ResourceManager.GetString("Ui_CreateTime", resourceCulture) ?? string.Empty;

        internal static string Ui_Creator => ResourceManager.GetString("Ui_Creator", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_Export => ResourceManager.GetString("Ui_CtxMenu_Export", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_OpenScorePage => ResourceManager.GetString("Ui_CtxMenu_OpenScorePage", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_OpenSourceFolder => ResourceManager.GetString("Ui_CtxMenu_OpenSourceFolder", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_RemoveFromList => ResourceManager.GetString("Ui_CtxMenu_RemoveFromList", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_SaveTo => ResourceManager.GetString("Ui_CtxMenu_SaveTo", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_SearchArtist => ResourceManager.GetString("Ui_CtxMenu_SearchArtist", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_SearchCreator => ResourceManager.GetString("Ui_CtxMenu_SearchCreator", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_SearchSource => ResourceManager.GetString("Ui_CtxMenu_SearchSource", resourceCulture) ?? string.Empty;

        internal static string Ui_CtxMenu_SearchTitle => ResourceManager.GetString("Ui_CtxMenu_SearchTitle", resourceCulture) ?? string.Empty;

        internal static string Ui_CurrentMapOffset => ResourceManager.GetString("Ui_CurrentMapOffset", resourceCulture) ?? string.Empty;

        internal static string Ui_DeleteExported => ResourceManager.GetString("Ui_DeleteExported", resourceCulture) ?? string.Empty;

        internal static string Ui_DesktopLyric => ResourceManager.GetString("Ui_DesktopLyric", resourceCulture) ?? string.Empty;

        internal static string Ui_EnsureRemoveAll => ResourceManager.GetString("Ui_EnsureRemoveAll", resourceCulture) ?? string.Empty;

        internal static string Ui_EnsureRemoveCollection => ResourceManager.GetString("Ui_EnsureRemoveCollection", resourceCulture) ?? string.Empty;

        internal static string Ui_Exit => ResourceManager.GetString("Ui_Exit", resourceCulture) ?? string.Empty;

        internal static string Ui_ExportAgain => ResourceManager.GetString("Ui_ExportAgain", resourceCulture) ?? string.Empty;

        internal static string Ui_Exported => ResourceManager.GetString("Ui_Exported", resourceCulture) ?? string.Empty;

        internal static string Ui_Exporting => ResourceManager.GetString("Ui_Exporting", resourceCulture) ?? string.Empty;

        internal static string Ui_ExportPath => ResourceManager.GetString("Ui_ExportPath", resourceCulture) ?? string.Empty;

        internal static string Ui_ExportTime => ResourceManager.GetString("Ui_ExportTime", resourceCulture) ?? string.Empty;

        internal static string Ui_Hint_SearchCollectionMusic3Dot => ResourceManager.GetString("Ui_Hint_SearchCollectionMusic3Dot", resourceCulture) ?? string.Empty;

        internal static string Ui_Hint_SearchPageBox => ResourceManager.GetString("Ui_Hint_SearchPageBox", resourceCulture) ?? string.Empty;

        internal static string Ui_Hue => ResourceManager.GetString("Ui_Hue", resourceCulture) ?? string.Empty;

        internal static string Ui_KugouMusic => ResourceManager.GetString("Ui_KugouMusic", resourceCulture) ?? string.Empty;

        internal static string Ui_Lightness => ResourceManager.GetString("Ui_Lightness", resourceCulture) ?? string.Empty;

        internal static string Ui_LimiterType => ResourceManager.GetString("Ui_LimiterType", resourceCulture) ?? string.Empty;

        internal static string Ui_LockLyric => ResourceManager.GetString("Ui_LockLyric", resourceCulture) ?? string.Empty;

        internal static string Ui_MapDifficulty => ResourceManager.GetString("Ui_MapDifficulty", resourceCulture) ?? string.Empty;

        internal static string Ui_Max30Char => ResourceManager.GetString("Ui_Max30Char", resourceCulture) ?? string.Empty;

        internal static string Ui_MiniMode => ResourceManager.GetString("Ui_MiniMode", resourceCulture) ?? string.Empty;

        internal static string Ui_MusicCount => ResourceManager.GetString("Ui_MusicCount", resourceCulture) ?? string.Empty;

        internal static string Ui_Nav_Collection => ResourceManager.GetString("Ui_Nav_Collection", resourceCulture) ?? string.Empty;

        internal static string Ui_Nav_Export => ResourceManager.GetString("Ui_Nav_Export", resourceCulture) ?? string.Empty;

        internal static string Ui_Nav_Library => ResourceManager.GetString("Ui_Nav_Library", resourceCulture) ?? string.Empty;

        internal static string Ui_Nav_Mine => ResourceManager.GetString("Ui_Nav_Mine", resourceCulture) ?? string.Empty;

        internal static string Ui_Nav_Music => ResourceManager.GetString("Ui_Nav_Music", resourceCulture) ?? string.Empty;

        internal static string Ui_Nav_Recent => ResourceManager.GetString("Ui_Nav_Recent", resourceCulture) ?? string.Empty;

        internal static string Ui_Nav_Search => ResourceManager.GetString("Ui_Nav_Search", resourceCulture) ?? string.Empty;

        internal static string Ui_Nav_Storyboard => ResourceManager.GetString("Ui_Nav_Storyboard", resourceCulture) ?? string.Empty;

        internal static string Ui_NeteaseMusic => ResourceManager.GetString("Ui_NeteaseMusic", resourceCulture) ?? string.Empty;

        internal static string Ui_Next => ResourceManager.GetString("Ui_Next", resourceCulture) ?? string.Empty;

        internal static string Ui_NextMusic => ResourceManager.GetString("Ui_NextMusic", resourceCulture) ?? string.Empty;

        internal static string Ui_No => ResourceManager.GetString("Ui_No", resourceCulture) ?? string.Empty;

        internal static string Ui_None => ResourceManager.GetString("Ui_None", resourceCulture) ?? string.Empty;

        internal static string Ui_Ok => ResourceManager.GetString("Ui_Ok", resourceCulture) ?? string.Empty;

        internal static string Ui_Open => ResourceManager.GetString("Ui_Open", resourceCulture) ?? string.Empty;

        internal static string Ui_OpenDesktopLyric => ResourceManager.GetString("Ui_OpenDesktopLyric", resourceCulture) ?? string.Empty;

        internal static string Ui_OpenFileFolder => ResourceManager.GetString("Ui_OpenFileFolder", resourceCulture) ?? string.Empty;

        internal static string Ui_Pause => ResourceManager.GetString("Ui_Pause", resourceCulture) ?? string.Empty;

        internal static string Ui_Play => ResourceManager.GetString("Ui_Play", resourceCulture) ?? string.Empty;

        internal static string Ui_Prev => ResourceManager.GetString("Ui_Prev", resourceCulture) ?? string.Empty;

        internal static string Ui_PrevMusic => ResourceManager.GetString("Ui_PrevMusic", resourceCulture) ?? string.Empty;

        internal static string Ui_QqMusic => ResourceManager.GetString("Ui_QqMusic", resourceCulture) ?? string.Empty;

        internal static string Ui_Saturation => ResourceManager.GetString("Ui_Saturation", resourceCulture) ?? string.Empty;

        internal static string Ui_SearchCollectionMusic3Dot => ResourceManager.GetString("Ui_SearchCollectionMusic3Dot", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets => ResourceManager.GetString("Ui_Sets", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_About => ResourceManager.GetString("Ui_Sets_About", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Common => ResourceManager.GetString("Ui_Sets_Common", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_AddToFavorite => ResourceManager.GetString("Ui_Sets_Content_AddToFavorite", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_AlreadyNewest => ResourceManager.GetString("Ui_Sets_Content_AlreadyNewest", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_AutoPlayOnProgramStartup => ResourceManager.GetString("Ui_Sets_Content_AutoPlayOnProgramStartup", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_BgDirectory => ResourceManager.GetString("Ui_Sets_Content_BgDirectory", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_CheckUpdate => ResourceManager.GetString("Ui_Sets_Content_CheckUpdate", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_ClickToUpdate => ResourceManager.GetString("Ui_Sets_Content_ClickToUpdate", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_CurrentVersion => ResourceManager.GetString("Ui_Sets_Content_CurrentVersion", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_DirGroupByArtist => ResourceManager.GetString("Ui_Sets_Content_DirGroupByArtist", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_DirGroupByMapper => ResourceManager.GetString("Ui_Sets_Content_DirGroupByMapper", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_DirGroupBySource => ResourceManager.GetString("Ui_Sets_Content_DirGroupBySource", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_DirNoGroup => ResourceManager.GetString("Ui_Sets_Content_DirNoGroup", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_DisplayAllLyrics => ResourceManager.GetString("Ui_Sets_Content_DisplayAllLyrics", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_EnableDesktopLyric => ResourceManager.GetString("Ui_Sets_Content_EnableDesktopLyric", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_EnableStrictMatching => ResourceManager.GetString("Ui_Sets_Content_EnableStrictMatching", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_ErrorWhileCheckingUpdate => ResourceManager.GetString("Ui_Sets_Content_ErrorWhileCheckingUpdate", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_ExitProgram => ResourceManager.GetString("Ui_Sets_Content_ExitProgram", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_Feedback => ResourceManager.GetString("Ui_Sets_Content_Feedback", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_HasNewVersion => ResourceManager.GetString("Ui_Sets_Content_HasNewVersion", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_LastCheckTime => ResourceManager.GetString("Ui_Sets_Content_LastCheckTime", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_LicenseInfo => ResourceManager.GetString("Ui_Sets_Content_LicenseInfo", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_MinToNotificationPanel => ResourceManager.GetString("Ui_Sets_Content_MinToNotificationPanel", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_MusicDirectory => ResourceManager.GetString("Ui_Sets_Content_MusicDirectory", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_Never => ResourceManager.GetString("Ui_Sets_Content_Never", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_NewVersion => ResourceManager.GetString("Ui_Sets_Content_NewVersion", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_PreferOriginLyricNeteaseOnly => ResourceManager.GetString("Ui_Sets_Content_PreferOriginLyricNeteaseOnly", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_PreferTranslateLyricNeteaseOnly => ResourceManager.GetString("Ui_Sets_Content_PreferTranslateLyricNeteaseOnly", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_PrivacyPolicy => ResourceManager.GetString("Ui_Sets_Content_PrivacyPolicy", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_ProjectUrl => ResourceManager.GetString("Ui_Sets_Content_ProjectUrl", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_ReleaseNote => ResourceManager.GetString("Ui_Sets_Content_ReleaseNote", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_ReleasePage => ResourceManager.GetString("Ui_Sets_Content_ReleasePage", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_RemindLater => ResourceManager.GetString("Ui_Sets_Content_RemindLater", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_ResumePlaylistOnProgramStartup => ResourceManager.GetString("Ui_Sets_Content_ResumePlaylistOnProgramStartup", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_RunOnStartup => ResourceManager.GetString("Ui_Sets_Content_RunOnStartup", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_Scanning3Dot => ResourceManager.GetString("Ui_Sets_Content_Scanning3Dot", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_SetAsDefaultOptions => ResourceManager.GetString("Ui_Sets_Content_SetAsDefaultOptions", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_SkipVersion => ResourceManager.GetString("Ui_Sets_Content_SkipVersion", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Content_SystemDefault => ResourceManager.GetString("Ui_Sets_Content_SystemDefault", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Export => ResourceManager.GetString("Ui_Sets_Export", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_HotKey => ResourceManager.GetString("Ui_Sets_HotKey", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Interface => ResourceManager.GetString("Ui_Sets_Interface", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Lyric => ResourceManager.GetString("Ui_Sets_Lyric", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Nav_About => ResourceManager.GetString("Ui_Sets_Nav_About", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Nav_Common => ResourceManager.GetString("Ui_Sets_Nav_Common", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Nav_Export => ResourceManager.GetString("Ui_Sets_Nav_Export", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Nav_HotKey => ResourceManager.GetString("Ui_Sets_Nav_HotKey", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Nav_Interface => ResourceManager.GetString("Ui_Sets_Nav_Interface", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Nav_Lyric => ResourceManager.GetString("Ui_Sets_Nav_Lyric", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Nav_Playing => ResourceManager.GetString("Ui_Sets_Nav_Playing", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Playing => ResourceManager.GetString("Ui_Sets_Playing", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_AudioPlayDevice => ResourceManager.GetString("Ui_Sets_Title_AudioPlayDevice", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_AutoPlay => ResourceManager.GetString("Ui_Sets_Title_AutoPlay", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_CloseWindow => ResourceManager.GetString("Ui_Sets_Title_CloseWindow", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_CustomSongPath => ResourceManager.GetString("Ui_Sets_Title_CustomSongPath", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_DesktopLyric => ResourceManager.GetString("Ui_Sets_Title_DesktopLyric", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_DirectoryGrouping => ResourceManager.GetString("Ui_Sets_Title_DirectoryGrouping", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_ExportPath => ResourceManager.GetString("Ui_Sets_Title_ExportPath", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_FileNamingFormat => ResourceManager.GetString("Ui_Sets_Title_FileNamingFormat", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_GlobalHitsoundDelay => ResourceManager.GetString("Ui_Sets_Title_GlobalHitsoundDelay", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_HotKeySettings => ResourceManager.GetString("Ui_Sets_Title_HotKeySettings", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_Language => ResourceManager.GetString("Ui_Sets_Title_Language", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_LyricSource => ResourceManager.GetString("Ui_Sets_Title_LyricSource", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_MatchMode => ResourceManager.GetString("Ui_Sets_Title_MatchMode", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_MinimalEffectMode => ResourceManager.GetString("Ui_Sets_Title_MinimalEffectMode", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_OsuDbLocation => ResourceManager.GetString("Ui_Sets_Title_OsuDbLocation", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_PlayProgress => ResourceManager.GetString("Ui_Sets_Title_PlayProgress", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_SoftwareUpdate => ResourceManager.GetString("Ui_Sets_Title_SoftwareUpdate", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_Startup => ResourceManager.GetString("Ui_Sets_Title_Startup", resourceCulture) ?? string.Empty;

        internal static string Ui_Sets_Title_Translation => ResourceManager.GetString("Ui_Sets_Title_Translation", resourceCulture) ?? string.Empty;

        internal static string Ui_Size => ResourceManager.GetString("Ui_Size", resourceCulture) ?? string.Empty;

        internal static string Ui_SongsClassifier => ResourceManager.GetString("Ui_SongsClassifier", resourceCulture) ?? string.Empty;

        internal static string Ui_StartScan => ResourceManager.GetString("Ui_StartScan", resourceCulture) ?? string.Empty;

        internal static string Ui_Storyboard => ResourceManager.GetString("Ui_Storyboard", resourceCulture) ?? string.Empty;

        internal static string Ui_Switch => ResourceManager.GetString("Ui_Switch", resourceCulture) ?? string.Empty;

        internal static string Ui_SwitchOff => ResourceManager.GetString("Ui_SwitchOff", resourceCulture) ?? string.Empty;

        internal static string Ui_SwitchOn => ResourceManager.GetString("Ui_SwitchOn", resourceCulture) ?? string.Empty;

        internal static string Ui_Tab_MusicList => ResourceManager.GetString("Ui_Tab_MusicList", resourceCulture) ?? string.Empty;

        internal static string Ui_Tab_MyCollection => ResourceManager.GetString("Ui_Tab_MyCollection", resourceCulture) ?? string.Empty;

        internal static string Ui_Title => ResourceManager.GetString("Ui_Title", resourceCulture) ?? string.Empty;

        internal static string Ui_Total => ResourceManager.GetString("Ui_Total", resourceCulture) ?? string.Empty;

        internal static string Ui_UnlockLyric => ResourceManager.GetString("Ui_UnlockLyric", resourceCulture) ?? string.Empty;

        internal static string Ui_VolumeDown => ResourceManager.GetString("Ui_VolumeDown", resourceCulture) ?? string.Empty;

        internal static string Ui_VolumeMaster => ResourceManager.GetString("Ui_VolumeMaster", resourceCulture) ?? string.Empty;

        internal static string Ui_VolumeMusic => ResourceManager.GetString("Ui_VolumeMusic", resourceCulture) ?? string.Empty;

        internal static string Ui_VolumeSample => ResourceManager.GetString("Ui_VolumeSample", resourceCulture) ?? string.Empty;

        internal static string Ui_VolumeSound => ResourceManager.GetString("Ui_VolumeSound", resourceCulture) ?? string.Empty;

        internal static string Ui_VolumeUp => ResourceManager.GetString("Ui_VolumeUp", resourceCulture) ?? string.Empty;

        internal static string Ui_Welcome_SelectDb => ResourceManager.GetString("Ui_Welcome_SelectDb", resourceCulture) ?? string.Empty;

        internal static string Ui_Welcome_Skip => ResourceManager.GetString("Ui_Welcome_Skip", resourceCulture) ?? string.Empty;

        internal static string Ui_Welcome_Subtitle => ResourceManager.GetString("Ui_Welcome_Subtitle", resourceCulture) ?? string.Empty;

        internal static string Ui_Welcome_Title => ResourceManager.GetString("Ui_Welcome_Title", resourceCulture) ?? string.Empty;

        internal static string Ui_Wenable_Watcher => ResourceManager.GetString("Ui_Wenable_Watcher", resourceCulture) ?? string.Empty;

        internal static string Ui_Win_Closing => ResourceManager.GetString("Ui_Win_Closing", resourceCulture) ?? string.Empty;

        internal static string Ui_Win_EditCollection => ResourceManager.GetString("Ui_Win_EditCollection", resourceCulture) ?? string.Empty;

        internal static string Ui_Win_NewCollection => ResourceManager.GetString("Ui_Win_NewCollection", resourceCulture) ?? string.Empty;

        internal static string Ui_Win_SelectCollection => ResourceManager.GetString("Ui_Win_SelectCollection", resourceCulture) ?? string.Empty;

        internal static string Ui_Win_SelectDifficulty => ResourceManager.GetString("Ui_Win_SelectDifficulty", resourceCulture) ?? string.Empty;

        internal static string Ui_Win_Sets => ResourceManager.GetString("Ui_Win_Sets", resourceCulture) ?? string.Empty;

        internal static string Ui_Yes => ResourceManager.GetString("Ui_Yes", resourceCulture) ?? string.Empty;
    }
}
